# weather_processor.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-processor
  template:
    metadata:
      labels:
        app: weather-processor
    spec:
      containers:
      - name: weather-processor
        image: maheshgaikwad21/weather_processor-app:latest
        ports:
        - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: weather-processor
spec:
  selector:
    app: weather-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort 